// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
)

type User struct {
	UserID       int32
	Username     string
	PasswordHash string
	Email        string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type UserAddress struct {
	UserAddressID int32
	UserID        int32
	StreetAddress string
	HouseNumber   sql.NullInt32
	Complement    sql.NullString
	City          string
	Zone          string
	District      sql.NullString
	PostalCode    string
	Country       string
}

type UserProfile struct {
	ProfileID   int32
	FirstName   sql.NullString
	LastName    sql.NullString
	PhoneNumber sql.NullString
	DateOfBirth sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	UserID      int32
	AddressID   int32
}
